travis:
  secure:
    BINSTAR_TOKEN: rxuqyD3+NpG6xyeC+qXQjQDXX5pOt4ZQrkrOvnGZb0EaTw2xwh6A7WTA85S9U0b5pERVajSHXugpRLt7jAcwpZmq2+bmp6etr8/vkiDtIHhJOiXHnfbt9Sr+f/uX/PgX+vIfSLvMCeZ/Xx6Rszo9iCG0O/eFUUvrrh3qRgdF7BINMrF+EpaWHjmshQ8rFEDGg09YF/oLfKCkMq3mpevg9J0PPQSIX0KXhC6sG4UtG17dTvA61Lepbenz6kRtajZXOIqmF9fJTze1kwC1NACf5gjSA1oa7GYQXc2/oQul3/T6CGw6nS6bAFTroKB0JcOoZnSf4iTeMCkrbT/JPjTOA8Q+KBgY98I34PFwY3E/Sx2/YThTg+AfX3b4W3z7AHYDgw6q32ddzsVYDIdd3cHImSQOByBmFZ9VQ5oXKm7Qd6oC3KjAfmvcBCIWYtshUqcGadC+IdgLjqUR/Bv3efRBvpuAqlV2A5pCM2wIBI+rsnwEimXXLAebIp/+aX9OeQiTvBNBBFQIIiHO+KDw9M0duuD/nCtieIHhNZTzGe/Ewb5UXAJPlByUiKKpA5++oVW/zwmGutX9K+WAJ/BvNhRWKUOL5J/gDRcWNRa4zzKBSeje4ROyK0W0gHOQlFkcKuoIKtRZaeRuiy20v3nK//wA5vYn8lpDwbDt5XqgbHJEXgs=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
conda_forge_output_validation: true
